### ISSUE TITLE
Adapt renamed methods from ahbicht PackageResolver

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/ahbicht-functions-python-client#16]
If https://github.com/Hochfrequenz/ahbicht/issues/157 renames anything, we'll have to switch to the new naming here (in the client), too.

## Todos
- [ ] either wait for dependabot or update manually to the new ahbicht release
- [ ] adapt the new naming
- [ ] create a new release (of the client)
