### ISSUE TITLE
Harmonize Condition and Package Resolver Constructors

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/ahbicht-functions-python-client#17]
As of now the signatures differ a little bit (for now obvious reason):

The package resolver only tkaes the base url as argument and the format(version) is set later:
https://github.com/Hochfrequenz/ahbicht-functions-python-client/blob/6863f0d00f5e70b2bed57bc5d409530b21a227ae/src/ahbichtfunctionsclient/__init__.py#L32

but the condition resolver also expects the format(version) in the constructor:
https://github.com/Hochfrequenz/ahbicht-functions-python-client/blob/6863f0d00f5e70b2bed57bc5d409530b21a227ae/src/ahbichtfunctionsclient/__init__.py#L60

No matter how we do it, it should at least be consistent.

## Todos
- [ ] harmonize and update tests accordingly
- [ ] Ensure that the updated package resolver (if it was updated at all) still behaves like a package resolver (but I guess this will be the case)
- [ ] create a new release
